{
  imports = [
    ./fuzzel.nix
    ./hypridle.nix
    ./hyprland-desktop.nix
    ./hyprland-laptop.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./niri.nix
    ./programs.nix
    ./swaylock.nix
    ./systemd.nix
    ./theming.nix
    ./wleave.nix
    ./xdg.nix
    ./wm-common.nix
    ./zsh.nix
  ];
}
