--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ben/wallpaper/sundown-over-water.jpg"

-- Special
background="#0c0d15"
foreground="#ebc4cb"
cursor="#ebc4cb"

-- Colors
color0="#0c0d15"
color1="#E06564"
color2="#F29271"
color3="#55618B"
color4="#B97390"
color5="#7783A9"
color6="#A68BB1"
color7="#ebc4cb"
color8="#a4898e"
color9="#E06564"
color10="#F29271"
color11="#55618B"
color12="#B97390"
color13="#7783A9"
color14="#A68BB1"
color15="#ebc4cb"
