# Shell variables
# Generated by 'wal'
wallpaper='/home/ben/wallpaper/sundown-over-water.jpg'

# Special
background='#0c0d15'
foreground='#ebc4cb'
cursor='#ebc4cb'

# Colors
color0='#0c0d15'
color1='#E06564'
color2='#F29271'
color3='#55618B'
color4='#B97390'
color5='#7783A9'
color6='#A68BB1'
color7='#ebc4cb'
color8='#a4898e'
color9='#E06564'
color10='#F29271'
color11='#55618B'
color12='#B97390'
color13='#7783A9'
color14='#A68BB1'
color15='#ebc4cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
